config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  apipie
  ActiveAdmin.routes(self)

  root to: 'home#index'
  devise_for :users, controllers: { confirmations: "confirmations", omniauth_callbacks: 'omniauth_callbacks' }

  resources :users do
    post 'upload_photo', on: :collection
  end

  resources :shows do
    get 'payment', on: :member
  end
  resources :pictures do
    post 'destroy', on: :member, as: 'destroy'
  end

  namespace :api do
    namespace :v1 do
      resources :users, :defaults => { :format => 'json' } do
        get 'search', on: :collection
        post 'pictures', on: :collection
        get 'list/pictures', to: 'users#list_pictures', on: :collection
        delete 'picture', to: 'users#destroy_pictures', on: :collection
        get 'artist', on: :collection
        post 'profile_picture', to: 'users#profile_picture', on: :collection
        delete 'disconnect-stripe', to: 'users#disconnect_stripe', on: :collection
      end
      resources :shows, :defaults => { :format => 'json' } do
        post 'toggle_active', on: :member
        get 'arts', on: :collection
        get 'search', on: :collection
      end
      resources :pictures, :defaults => { :format => 'json' }
      resources :bookings, :defaults => { :format => 'json' } do
        post 'change_status', on: :member
        post 'apply_coupon'
      end
      resources :arts, :defaults => { :format => 'json' }
      resources :showcases
      resources :user_availabilities, path: :availabilities, only: [:index, :show, :create, :destroy]
      resources :credit_cards, only: [:create] do
        patch 'make_default', on: :member
      end
    end
  end

  get '/dashboard', to: 'dashboard#index'
  get '/dashboard/profile', to: 'dashboard#profile', as: 'profile_dashboard'
  get '/dashboard/messages', to: 'dashboard#messages', as: 'messages_dashboard'
  get '/dashboard/shows', to: 'dashboard#shows', as: 'shows_dashboard'
  get '/dashboard/performances', to: 'dashboard#performances', as: 'performances_dashboard'
  get '/dashboard/account', to: 'dashboard#account', as: 'account_dashboard'
  patch '/dashboard/update', to: 'dashboard#update', as: 'update_dashboard'
  get '/dashboard/bookings', to: 'dashboard#bookings', as: 'bookings_dashboard'
  post '/contact', to: 'home#contact', as: 'home_contact'
  post '/society', to: 'home#society', as: 'home_society'

end

app/models/show.rb
class Show < ActiveRecord::Base

  COMMISSION = 1.1
  
  belongs_to :cover_picture, class_name: 'Picture'

  belongs_to :user
  has_one :art, through: :user
  has_many :languages, through: :user

  has_many   :bookings
  has_many   :pictures  , dependent: :destroy , as: :imageable
  has_many :reviews, through: :bookings
  has_many :ratings, through: :reviews

  just_define_datetime_picker :published_at
  validates :length, :title, :description, :price, presence: true
  accepts_nested_attributes_for :pictures, allow_destroy: true

  after_save :set_cover_picture
  before_save :update_rating

  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  def as_indexed_json options={}
    self.as_json({
                   only: [:title, :description]
    })
  end

  def reviews_max_3
    reviews.first(3)
  end

  def spectators
    spect = ""
    if min_attendees && max_spectators
      spect += "from " + min_attendees.to_s + " "
      spect += "to " + max_spectators.to_s
      spect.slice(0,1).capitalize + spect.slice(1..-1)
    elsif !min_attendees && !max_spectators
      spect = "Indifférent"
    elsif !min_attendees
      spect = "Maximum " + max_spectators.to_s
    elsif !max_spectators
      spect = "Minimum " + min_attendees.to_s
    end
  end

  def duration
    if length > 59
      return (length / 60).to_s + "h " + (length % 60).to_s.to_s + "min"
    else
      return length.to_s + "min"
    end
    ''
  end

  def toggle_active
    if user && user.addresses.any? && user.phone_number.present?
      self.active = !self.active
      self.save
    else
      if user.addresses.empty?
        self.errors.add(:address, I18n.t('activerecord.errors.messages.addresses_is_empty'))
      elsif user.phone_number.blank?
        self.errors.add(:phone_number, I18n.t('activerecord.errors.messages.phone_number_is_empty'))
      end
    end
  end

  def pictures=(array)
    array.each do |file|
      pictures.build(image: file)
    end
  end

  private

  def set_cover_picture
    picture = self.pictures.select { |p| p.selected }.first
    if picture && picture.id != cover_picture_id
      self.cover_picture = picture
      self.save
    end
  end

  def update_rating
    self.rating = [ratings.average(:value).to_f, 5].min
  end

end

# == Schema Information
#
# Table name: shows
#
#  id               :integer          not null, primary key
#  title            :string
#  length           :integer
#  surface          :integer
#  description      :text
#  price            :float
#  max_spectators   :integer
#  starts_at        :string
#  ends_at          :string
#  active           :boolean
#  published_at     :datetime
#  cover_picture_id :integer
#  user_id          :integer
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  rating           :float
#  price_person     :boolean
#  min_attendees    :integer
#
# Indexes
#
#  index_shows_on_cover_picture_id  (cover_picture_id)
#  index_shows_on_user_id           (user_id)
#

app/controllers/api/v1/shows_controller.rb
class Api::V1::ShowsController < Api::BaseController
  before_action :authenticate_user!, except: [:search, :show]

  def create
    @show = current_user.shows.create(show_params)
    respond_with :api, :v1, @show
  end

  def show
    @show = Show.find(params[:id])
    respond_with :api, :v1, @show
  end

  def update
    @show = current_user.shows.find(params[:id])
    @show.update_attributes show_params
    respond_with :api, :v1, @show
  end

  def toggle_active
    @show = current_user.shows.find(params[:id])
    @show.toggle_active
    respond_with :api, :v1, @show
  end

  def index
    @shows = current_user.shows
    respond_with :api, :v1, @shows
  end

  def search
    @shows = ShowSearchService.new(query: params[:q],
                                   price_min: params[:price0],
                                   price_max: params[:price1])
                              .results
    respond_with :api, :v1, @shows
  end

  def destroy
    @show = current_user.shows.find(params[:id])
    @show.destroy
    respond_with :api, :v1, @show
  end

  private

  def show_params
    params.require(:show).permit(:min_attendees, :max_spectators, :length, :title, :description, :price, :price_person, :cover_picture_id, :starts_at, :ends_at, :date_at, pictures_attributes: [ :src, :_destroy, :id, :selected ])
  end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  before_action :set_show, only: [:show, :edit, :payment]
  before_action :authenticate_user!, except: [:index]

  # GET /shows
  # GET /shows.json
  def index
  end

  # GET /shows/1
  # GET /shows/1.json
  def show

  end

  # GET /shows/new
  def new
    @show = Show.new
  end

  # GET /shows/1/edit
  def edit
    render 'new'
  end

  def payment

  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_show
      @show = Show.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def show_params
      return_params = params[:show].permit(:art_id, :max_spectators, :length, :title, :description, :price, :cover_picture_id, :starts_at, :ends_at, language_ids: [])
    end
end

app/views/shows/_form.html.slim
= simple_form_for(show) do |f|
  = f.error_notification

  .form-inputs

  .form-actions
    = f.button :submit

app/views/shows/_tabs.html.slim
.col-md-3
  br
  ul.nav.nav-pills.nav-stacked
    li[ng-class="{ active: step == 1 }"]
      a[href="" ng-click="tabClick(1)"]= "Description"
    li[ng-class="{ active: step == 2 }"]
      a[href="" ng-click="tabClick(2)"]= "Photos"
    li[ng-class="{ active: step == 3 }"]
      a[href="" ng-click="tabClick(3)"]= "Cover Photo"
    li[ng-class="{ active: step == 4 }"]
      a[href="" ng-click="tabClick(4)"]= "Shedules"

app/views/shows/cover_picture.html.slim
.container.show[data-show-id=(@show.id)]
  .row
    = render "tabs"
    .col-md-9
      form#cover_picture_form[action=(show_path(@show) + ".json")]
        .form-inputs
          fieldset
            legend= "Cover Photo"
            p= "Choose a cover photo for your show"
            br
            .row
              - @show.pictures.each do |picture|
                .col-sm-4.col-md-3
                  .thumbnail.cover-photo
                    label
                      img[src=(picture.image.url(:medium))]
                      .caption
                        input[name="show[cover_picture_id]" id="cover_picture_#{picture.id}" value=(picture.id) type="radio" onclick="$('#continue').prop('disabled', false);"]
                        '
                        = "Cover photo"

        .form-actions
          .form-group
            input#continue.btn.btn-default[type="submit" value="Continue" disabled=(true)]

app/views/shows/edit.html.slim
h1 Editing show

== render 'form', show: @show

= link_to 'Show', @show
'|
= link_to 'Back', shows_path

app/views/shows/index.html.slim
.container[ng-controller="ShowSearchController"]
  .results[ng-if="mode == 'list'"]
    .row
      .col-md-3
        form.form-inline
          .form-group
            input.form-control[type="text" placeholder="Search" ng-model="filter.text" ng-enter="search()"]
            button.btn.btn-default[ng-click="search()"]
              i.glyphicon.glyphicon-search

        hr

        .price
          filter-price[min="10" max="100000" model="filter.price"]

        .checkbox[ng-repeat="art in arts"]
          label
            input[type="checkbox" ng-model="art.checked" ng-click="search()"]
            '
            | {{ art.title }}

      .col-md-9
        .row
          .col-md-12
            dir-pagination-controls.pull-right
        .row
          .col-md-4[dir-paginate="show in shows | itemsPerPage:21"]
            a.show-search.thumbnail[href="" ng-click="modeDetails(show)"]
              img[ng-src="{{ show.coverPicture.urlMedium }}" width="300" height="300"]
              .caption
                img.user[ng-src="{{ show.userPictureUrl }}"]
                h4= "{{ show.title }}"
                .rating[ng-if="show.rating"]
                  i.glyphicon.glyphicon-star[ng-repeat="k in range(Math.round(show.rating)) track by $index"]
                  i.glyphicon.glyphicon-star-empty[ng-repeat="k in range(5 - Math.round(show.rating)) track by $index"]
                .length
                  | {{ show.length }} minutes
                .price
                  | {{ show.price | currency:undefined:0 }}

        .row
          .col-md-12
            dir-pagination-controls.pull-right


  .details[ng-if="mode == 'detail'"]
    a[href="" ng-click="modeList()"]
      i.glyphicon.glyphicon-arrow-left
      '
      | Back to List
    hr
    .row
      .col-md-3
        .show-slider
          .thumbnail.main-image
            .left[ng-click="prevPicture()"]
              .badge
                i.glyphicon.glyphicon-chevron-left
            img[ng-src="{{ show.coverPicture.urlMedium }}"]
            .right[ng-click="nextPicture()"]
              .badge
                i.glyphicon.glyphicon-chevron-right
          .row
            .col-md-3[ng-repeat="picture in show.pictures" style="padding: 3px;"]
              a.thumbnail[href="" ng-click="changePicture(picture)"]
                img[ng-src="{{ picture.urlThumb }}"]
      .col-md-9
        .row
          .col-md-2
            .thumbnail.pull-left
              img[ng-src="{{ show.userPictureUrl }}"]
            .user-name.text-center
              | {{ show.user.fullName }}
          .col-md-10
            .rating[ng-if="show.rating"]
              i.glyphicon.glyphicon-star[ng-repeat="k in range(Math.round(show.rating)) track by $index"]
              i.glyphicon.glyphicon-star-empty[ng-repeat="k in range(5 - Math.round(show.rating)) track by $index"]
            h3= "{{ show.title }}"
            p.price
              | {{ show.price | currency:undefined:0 }}
            p.length
              | {{ show.length }} minutes
            p.available
              | Disponible de
              '
              b
                | {{ show.startsAt | amParse:'YYYY-MM-DD HH:mm:ss ZZ' | amDateFormat:'LLL' }}
              '
              span[ng-if="show.endsAt"]
                | à
                '
                b
                  | {{ show.endsAt | amParse:'YYYY-MM-DD HH:mm:ss ZZ' | amDateFormat:'LLL' }}
            dl
              dt Bio
              dd
                | {{ show.user.bio }}
            dl
              dt Description
              dd
                | {{ show.description }}

            form.form-horizontal[name="bookingForm"]
              fieldset
                legend Submit a Booking

                input-datetime[label="Choose Date and Time" model="booking.date" start-date="{{ booking.startDate }}" end-date="{{ show.endsAt }}" date-format="d M, yyyy hh:ii"]
                input-integer[label="Number of guests" model="booking.spectators" min="1" max="show.maxSpectators"]

              .row
                .col-md-9.col-md-offset-3
                  button.btn.btn-default[ng-click="bookingForm.$valid && submitBooking()"]
                    | Submit

app/views/shows/new.html.slim
.container[ng-controller="ShowController" ng-init="load(#{@show.id})"]
  .row
    = render "tabs"
    .col-md-9
      form.show.form-horizontal[novalidate name="showForm"]
        .form-inputs[ng-if="step == 1"]
          fieldset
            legend= "My Show Details"
            p= "Your show will be visible on the site once you have downloaded your photos and complete details of your profile"
            br
            input-select[label="Art" model="show.artId" required data-collection=(Art.order(:title).all.map {|a| { name: a.title, value: a.id }}.to_json)]
            input-integer[label="Max Spectators" model="show.maxSpectators" required]
            input-integer[label="Duration in minutes" model="show.length" required]
            input-string[label="Title" model="show.title" required]
            input-text[label="Description" model="show.description" required]
            / input-select[label="Language" model="show.languageId" data-collection=(Language.order(:title).all.map {|a| { name: a.title, value: a.id }}.to_json) required]
          fieldset
            legend= "Price"
            input-integer[label="Price" model="show.price" required]
            / = f.input :price

        .form-inputs[ng-if="step == 2"]
          fieldset
            legend= "Add Photos"
            p= "Add photos from your Show"
            br
            .row
              .col-xs-6.col-md-3[ng-repeat="picture in show.pictures" ng-hide="picture._destroy == 1"]
                .thumbnail
                  img[ng-src="{{picture.src}}" image-crop width="300" height="300"]
                  .caption
                    .actions.pull-right
                      a[href="#" ng-click="removePicture($index)"]
                        i.glyphicon.glyphicon-trash
                  .clearfix
            br
            input-images-button[label="Upload photos" model="show.pictures" required]

        .form-inputs[ng-if="step == 3"]
          fieldset
            legend= "Cover Photo"
            p= "Choose a cover photo for your show"
            br
            .row
              .col-xs-6.col-md-3[ng-repeat="picture in show.pictures" ng-hide="picture._destroy == 1"]
                a.thumbnail[href="" ng-click="selectCoverPhoto(picture)"]
                  img[ng-src="{{picture.src}}" image-crop width="300" height="300"]
                  .caption
                    i.glyphicon.glyphicon-ok[ng-show="picture.selected"]
                    '
                    = "Cover Photo"

        .form-inputs[ng-if="step == 4"]
          fieldset
            legend= "What at time?"
            p= "Over what time slot can the spectators order your show?"
            br
            input-time[label="Starts at" model="show.startsAt" required]
            input-time[label="Ends at" model="show.endsAt" required]

        hr
        .form-actions
          .form-group
            .row
              .col-md-9.col-md-offset-3
                button#continue.btn.btn-default[ng-click="prevStep(showForm)" ng-show="step > 1"]
                  = "Back"
                '
                button#continue.btn.btn-default[ng-click="nextStep(showForm)" ng-show="step < 4"]
                  = "Continue"
                button#finish.btn.btn-default[ng-click="finish()" ng-show="step == 4"]
                  i.glyphicon.glyphicon-refresh.glyphicon-refresh-animate[ng-show="show.pending"]
                  '
                  = "Finish"

app/views/shows/payment.html.slim
.container[ng-controller="ShowPaymentController" ng-init="init(#{@show.id})"]
  .row
    .col-md-3.col-md-offset-2
      img[ng-src="{{ show.coverPictureUrl }}"]
      h3
        | {{ show.title }}
      / {{ show.date. }}

app/views/shows/photos.html.slim
.container.show[data-show-id=(@show.id)]
  .row
    = render "tabs"
    .col-md-9
      form
        .form-inputs
          fieldset
            legend= "Add Photos"
            p= "Add photos from your Show"
            br
            .row.form-group
              label.col-md-3.text-right
                = "Select photos"
              .col-md-9
                input#show_image.file-loading[type="file" multiple data-show-id=(@show.id) data-url=(pictures_path(imageable_type: 'Show', imageable_id: @show.id))]

        .form-actions
          .form-group
            .row
              .col-md-9.col-md-offset-3
                button#continue.btn.btn-default[disabled=(@show.pictures.count == 0) data-href=(cover_picture_show_path(@show))]
                  = "Continue"

app/views/shows/shedules.html.slim
.container.show[data-show-id=(@show.id)]
  .row
    = render "tabs"
    .col-md-9
      = simple_form_for @show do |f|
        .form-inputs
          fieldset
            legend= "What at time?"
            p= "Over what time slot can the spectators order your show?"
            br
            .row
              .col-md-5
                = f.input :starts_at do
                  = f.select :starts_at, 24.times.to_a.inject([]) {|a, i| h = i.to_s.rjust(2, '0'); a << h + ':00'; a << h + ':30' }
              .col-md-5
                = f.input :ends_at do
                  = f.select :ends_at, 24.times.to_a.inject([]) {|a, i| h = i.to_s.rjust(2, '0'); a << h + ':00'; a << h + ':30' }

        .form-actions
          .form-group
            input#continue.btn.btn-default[type="submit" value="Publish" disabled=(true)]

app/views/shows/show.html.slim
p#notice = notice


= link_to 'Edit', edit_show_path(@show)
'|
= link_to 'Back', shows_path